version: '3'
services:
  mariadb:
    image: mariadb
    container_name: mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: bearman
      MYSQL_DATABASE: mydb
      MYSQL_USER: bearman
      MYSQL_PASSWORD: bearman
    ports:
      - "3306:3306"
    volumes:
      - ./data.db:/var/lib/mysql
    command: --max_allowed_packet=256M  # Augmenter la taille du paquet maximum si nécessaire
    mem_limit: 4g  # Limite de mémoire du conteneur à 4 Go
